name: hrm-ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    services:
      postgres:
        image: postgres:11.7
        env:
          POSTGRES_USER: hrm
          POSTGRES_DB: hrmdb
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup database tables
      uses: n1ru4l/psql-action@v1
      with:
        POSTGRES_HOST: localhost
        POSTGRES_USER: hrm
        POSTGRES_PASSWORD: postgres
        POSTGRES_PORT: 5432 
        DATABASE_DUMP_PATH: "/dump.sql"
    - name: Install Packages
      run: npm install
    - name: Run Lint
      run: npm run lint --if-present
    - name: Run Tests
      run: npm test
      env:
        CI: true
        API_KEY: secret
        RDS_PASSWORD: postgres
